BidR/Models/Database/User.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using BidR.Models.View;
using Microsoft.AspNetCore.Identity;

namespace BidR.Models.Database
{
    public enum Gender
    {
        Male = 0,
        Female = 1
    }

    public class User : IdentityUser
    {
        [Required]
        public string firstName { get; set; }
        [Required]
        public string lastName { get; set; }
        [Required]
        public Gender gender { get; set; }
        [Required]
        public bool deleted { get; set; }
        [Required]
        public uint tokens { get; set; }

        //konkurentnost
        [Timestamp]
        public byte[] RowVersion { get; set; }

        public ICollection<Order> orders;
        public ICollection<Auction> auctions;
        public ICollection<Licitation> licitations;
    }

    public class UserProfile : Profile
    {
        public UserProfile()
        {
            base.CreateMap<RegisterModel, User>().
                ForMember(
                    destination => destination.Email,
                    options => options.MapFrom(data => data.email)
                ).
                ForMember(
                    destination => destination.UserName,
                    options => options.MapFrom(data => data.username)
                );
        }
    }

}

BidR/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BidR.Models.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BidR.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private BidRContext context;
        private UserManager<User> userManager;
        private SignInManager<User> signInManager;

        public AdminController(BidRContext context, UserManager<User> userManager,
            SignInManager<User> signInManager)
        {
            this.context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return this.Auctions();
        }

        public IActionResult Users()
        {
            List<User> users = this.context.Users.Where(user => user.UserName != "administrator" && user.deleted == false).ToList();
            return View(users);
        }

        public IActionResult Auctions()
        {
            List<Auction> auctions = this.context.auctions.Where(auction => auction.state == AuctionState.DRAFT).Include(auction => auction.User).ToList();
            return View(auctions);
        }

        public async Task<IActionResult> DeleteUser(string username)
        {
            if (username == null)
            {
                return NotFound();
            }

            var user = await context.Users
                .FirstOrDefaultAsync(m => m.UserName == username);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string Id)
        {
            var user = await context.Users.FindAsync(Id);
            user.deleted = true;

            try
            {
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                foreach (var entry in ex.Entries)
                {
                    var databaseValues = entry.GetDatabaseValues();
                    databaseValues["deleted"] = 1;
                    entry.OriginalValues.SetValues(databaseValues);
                }
            }

            //update auctions
            List<Auction> auctions = this.context.auctions.Where(auction => auction.UserId == Id).ToList();

            foreach (Auction auction in auctions)
            {
                auction.state = AuctionState.EXPIRED;
            }

            try
            {
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                foreach (var entry in ex.Entries)
                {
                    var databaseValues = entry.GetDatabaseValues();
                    databaseValues["state"] = AuctionState.EXPIRED;
                    entry.OriginalValues.SetValues(databaseValues);
                }
            }

            return RedirectToAction(nameof(Users));
        }

        public async Task<IActionResult> AuctionPreview(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var auction = await context.auctions.Include(auction => auction.User)
                .FirstOrDefaultAsync(m => m.Id == Id);
            if (auction == null || auction.state != AuctionState.DRAFT)
            {
                return NotFound();
            }

            return View(auction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AuctionConfirmed(int Id)
        {
            var auction = await context.auctions.FindAsync(Id);
            auction.state = AuctionState.READY;

            try
            {
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                foreach (var entry in ex.Entries)
                {
                    var databaseValues = entry.GetDatabaseValues();
                    databaseValues["state"] = AuctionState.READY;
                    entry.OriginalValues.SetValues(databaseValues);
                }
            }

            return RedirectToAction(nameof(Auctions));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AuctionDeleted(int Id)
        {
            var auction = await context.auctions.FindAsync(Id);
            auction.state = AuctionState.DELETED;

            try
            {
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                foreach (var entry in ex.Entries)
                {
                    var databaseValues = entry.GetDatabaseValues();
                    databaseValues["state"] = AuctionState.DELETED;
                    entry.OriginalValues.SetValues(databaseValues);
                }
            }

            return RedirectToAction(nameof(Auctions));
        }
    }
}

BidR/Controllers/TokenController.cs
using System.Collections.Generic;
using BidR.Models.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System;
using Microsoft.EntityFrameworkCore;

namespace BidR.Controllers
{
    [Authorize(Roles = "User")]
    public class TokenController : Controller
    {
        private BidRContext context;
        private UserManager<User> userManager;

        public TokenController(BidRContext context, UserManager<User> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            List<Package> packages = this.context.packages.ToList();
            return View(packages);
        }

        [HttpGet]
        public IActionResult BuyPackage(int Id)
        {
            Package package = this.context.packages.Where(package => package.Id == Id).First();
            return View(package);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BuyPackageAsync(int Id, int? dummy)//dummy samo zbog potpisa fje
        {
            Package package = context.packages.Find(Id);
            User user = await userManager.GetUserAsync(User);
            Order order = new Order
            {
                UserId = user.Id,
                User = user,
                PackageId = package.Id,
                Package = package,
                timestampCreated = DateTime.Now
            };
            user.tokens = user.tokens + package.tokens;

            try
            {
                await this.context.orders.AddAsync(order);
                await this.context.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                foreach (var entry in ex.Entries)
                {//check this out
                    var databaseValues = entry.GetDatabaseValues();
                    var newUser = (User)databaseValues.ToObject();
                    databaseValues["tokens"] = newUser.tokens + package.tokens;
                    entry.OriginalValues.SetValues(databaseValues);
                }
            }

            return Json("Done");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> OrderList()
        {
            User user = await userManager.GetUserAsync(User);
            List<Order> orders = await context.orders.Where(order => order.UserId == user.Id).OrderByDescending(order => order.timestampCreated).Include(order => order.Package).ToListAsync();
            return Json(orders);
        }
    }
}

BidR/Views/Shared/Nav.cshtml
@using Microsoft.AspNetCore.Identity;
@using BidR.Models.Database;
@using System.Security.Claims;

@inject SignInManager<User> signInManager;
@inject UserManager<User> userManager;
@inject BidRContext context;

<ul class="navbar-nav flex-grow-1">
    @if (signInManager.IsSignedIn( User ))
    {
        User loggedUsers = await this.userManager.GetUserAsync(base.User);
        IdentityUserRole<String> roleId = context.UserRoles.Where(role => role.UserId == loggedUsers.Id).FirstOrDefault();
        IdentityRole roleName = context.Roles.Where(role => role.Id == roleId.RoleId).FirstOrDefault();

        if (roleName.Name == "User")
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="MyAuctions">My auctions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="AuctionsWon">Auctions won</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="AddAuction">Add auction</a>
            </li>
        }
        else 
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Auctions">Auctions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Users">Users</a>
            </li>
        }
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="Index">Auctions</a>
        </li>
    }
</ul>

BidR/Views/Shared/SignalRScriptsPartial.cshtml
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/signalr/dist/browser/signalr.min.js"></script>

BidR/Views/Shared/User.cshtml
@using Microsoft.AspNetCore.Identity;
@using BidR.Models.Database;
@using System.Security.Claims;

@inject SignInManager<User> signInManager;
@inject UserManager<User> UserManager;
@inject BidRContext context;

@{
    User user = await UserManager.GetUserAsync(User);
    IdentityUserRole<String> roleId = null;
    IdentityRole roleName = null;
    if (user != null)
    {
        roleId = context.UserRoles.Where(role => role.UserId == user.Id).FirstOrDefault();
        roleName = context.Roles.Where(role => role.Id == roleId.RoleId).FirstOrDefault();
    }

    string fullName = user != null ? user.firstName + " " + user.lastName : "";
    /*foreach( Claim claim in User.Claims)
    {
        if(claim.Type.Equals ("fullName"))
        {
            fullName = claim.Value;
            break;
        }
    }*/
}

<ul class="navbar-nav">
    @if (signInManager.IsSignedIn( User ))
    {
        <input id="userName" type="hidden" value="@user.UserName" />
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="User" asp-action="Settings">Welcome, @fullName</a>
        </li> 
        @if(roleName != null && roleName.Name == "User")
        {
            <li class="nav-item"> 
                <a class="nav-link text-dark" asp-controller="Token" asp-action="Index"> <span id="availableTokens">@user.tokens</span> <img class="tokenPng pd-2" src="~/assets/Token.png" alt=""></a>
            </li>
        }
        <li class="nav-item">
            <form class="form-inline" asp-controller="User" asp-action="LogOut">
                <input type="submit" class="nav-link btn btn-link text-info" value="Log out" />
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="User" asp-action="LogIn">Log in</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="User" asp-action="Register">Register</a>
        </li>
    }
</ul>

BidR/Views/Shared/_AuctionGrid.cshtml
 @model cloudscribe.Pagination.Models.PagedResult<BidR.Models.Database.Auction>

@using Microsoft.AspNetCore.Identity;
@inject UserManager<User> userManager;

@using BidR.Models.Database;

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}

@{
    String[] stateText = {"DRAFT", "READY", "BID", "SOLD", "EXPIRED", "DELETED"};
    int[] pageSizes = {4, 12, 20, 24, 32};
}
<div class="row">
    @foreach (BidR.Models.Database.Auction auction in Model.Data)
    {
        User loggedUser = this.userManager.GetUserAsync(base.User).Result;
        string enable = "";
        if ( auction.state != AuctionState.OPEN || ( loggedUser != null && auction.User.Id == loggedUser.Id)) 
            enable = "disabled";
        var winner = auction.Winner != null ? auction.Winner.UserName : "-";
        DateTime localDate = DateTime.Now;
        TimeSpan timeSpan = auction.closedTimestamp.Subtract(localDate);
        string buttonText = stateText[(int)auction.state];
        if (auction.state != AuctionState.OPEN)
            timeSpan = localDate.Subtract(localDate);
        else
            timeSpan = auction.closedTimestamp.Subtract(localDate);

        <div class="col-3 auctionItems">
            <div class="auctionBox">
                <input type="hidden" class="auctionId" value="@auction.Id">
                <div  class="mb-3">
                    <a asp-controller="Auction" asp-action="AuctionDetails" asp-route-Id="@auction.Id">
                        <center><h3 class="auctionTitle">@auction.name</h3></center>
                    </a>
                </div>
                <div class = "auction-frame mb-2">
                    <img class="auction-picture" src="data:image/jpg;base64, @Convert.ToBase64String(auction.image)" />
                </div>
                <center><h2 class="auctionTime">@timeSpan.Days:@timeSpan.Hours:@timeSpan.Minutes:@timeSpan.Seconds</h2></center>
                <center><h3 class="auctionBidPrice green">@String.Format("{0:0.00}", auction.bidPrice)$</h3></center>
                <center><h3 id="price_@auction.Id" class="auctionCurrPrice">Price: @String.Format("{0:0.00}", auction.newPrice)$</h3></center>
                <center><h6 id="bidder_@auction.Id" class="auctionBidder">@winner</h6></center>
                <center><button id="button @auction.Id" class="btn btn-primary percent60 bidButton" @enable>@buttonText</button></center>
            </div>
        </div>
    }
</div>
<div class="row">
    <div class="col-6">
        Auctions per page:
        <select name="auctionsPerPage" id="auctionsPerPage">
            @foreach (int pSize in pageSizes)
            {
                if (pSize == Model.PageSize)
                {
                    <option value="@pSize" selected>@pSize</option>
                }
                else
                {
                    <option value="@pSize">@pSize</option>   
                }
            }
        </select>
    </div>
    <div class="col-6 d-flex justify-content-end">
        <partial name="_PaginationPartial", view-data="@ViewData" model="@Model" />
    </div>
</div>

@{await Html.RenderPartialAsync("SignalRScriptsPartial");}
<script src="~/js/pagination.js"></script>
<script src="~/js/bid.js"></script>

BidR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BidR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Auction" asp-action="Index">BidR</a>
                <partial name="Nav"></partial>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="User"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid d-flex justify-content-center">
        <main role="main" class="width90 pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BidR
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BidR/Views/Shared/_PaginationPartial.cshtml
<script type="text/javascript">
        
        function PagerRequestSuccess(data) {
            //console.log("This is the OnSuccessCallback: " + data);
            console.log("This is the OnSuccessCallback");
        }
        function PagerRequestFailure(request, error) {
            console.log("This is the OnFailure Callback:" + error);
        }
        
</script>

<cs-pager
    cs-paging-pagenumber="@(int)Model.PageNumber"
    cs-paging-totalitems="@(int)Model.TotalItems"
    cs-paging-pagesize="@Model.PageSize"
    cs-ajax-target="#auctions"
    cs-ajax-success="PagerRequestSuccess"
    cs-ajax-failure="PagerRequestFailure"
    cs-pagenumber-param="pageNumber"
    asp-controller="@ViewData["Controller"]"
    asp-action="@ViewData["Action"]"
    cs-pager-li-current-class="page-item active"
    cs-pager-li-other-class="page-item"
    cs-pager-li-non-active-class="page-item disabled"
    cs-pager-link-current-class="page-link"
    cs-pager-link-other-class="page-link"
></cs-pager>

BidR/Views/Shared/_SearchBarPartial.cshtml
<div class="container-fluid">
    <div class="row mb-4 d-flex justify-content-center">
        <div class="col-6 d-flex justify-content-center">
            <b>Search</b>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-6 d-flex justify-content-center">
            Name
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col mt-2 mb-3 d-flex justify-content-center">
            <input type="text" id="auctionTitle" />
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-6 d-flex justify-content-center">
            Price
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-5 d-flex justify-content-center">
            Low:
        </div>
        <div class="col-5 d-flex justify-content-center" >
            High:
        </div>
    </div>
    <div class="row">
        <div class="col-6 mt-2 mb-3 pr-1">
            <input type="number" id="auctionPriceLow" />
        </div>
        <div class="col-6 mt-2 mb-3 pl-1">
            <input type="number" id="auctionPriceHigh" />
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-6 d-flex justify-content-center">
            Status
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-6 mt-2 mb-3 d-flex justify-content-center">
            <select name="status" id="auctionStatus">
            </select>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-6 mt-2 mb-3 d-flex justify-content-center">
            <button id="searchButton" type="button" class="btn btn-success">SEARCH</button>
        </div>
    </div>
</div>